# -*- coding: utf-8 -*-
"""DBscan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRUl4meUViaGLJXS68Y_B5omySzMpkDa

# About this Dataset

Social Media vs Productivity — Realistic Behavioral Dataset (30,000 Users)
This dataset explores how daily digital habits — including social media usage, screen time, and notification exposure — relate to individual productivity, stress, and well-being.

🔍 What’s Inside?
The dataset contains 30,000 real-world-style records simulating behavioral patterns of people with various jobs, social habits, and lifestyle choices. The goal is to understand how different digital behaviors correlate with perceived and actual productivity.


🧾 Columns & Feature Info
Column Name	Description
age	Age of the individual (18–65 years)
gender	Gender identity: Male, Female, or Other
job_type	Employment sector or status (IT, Education, Student, etc.)
daily_social_media_time	Average daily time spent on social media (hours)
social_platform_preference	Most-used social platform (Instagram, TikTok, Telegram, etc.)
number_of_notifications	Number of mobile/social notifications per day
work_hours_per_day	Average hours worked each day
perceived_productivity_score	Self-rated productivity score (scale: 0–10)
actual_productivity_score	Simulated ground-truth productivity score (scale: 0–10)
stress_level	Current stress level (scale: 1–10)
sleep_hours	Average hours of sleep per night
screen_time_before_sleep	Time spent on screens before sleeping (hours)
breaks_during_work	Number of breaks taken during work hours
uses_focus_apps	Whether the user uses digital focus apps (True/False)
has_digital_wellbeing_enabled	Whether Digital Wellbeing is activated (True/False)
coffee_consumption_per_day	Number of coffee cups consumed per day
days_feeling_burnout_per_month	Number of burnout days reported per month
weekly_offline_hours	Total hours spent offline each week (excluding sleep)
job_satisfaction_score	Satisfaction with job/life responsibilities (scale: 0–10)

# step1 Data Collection

In this step, we import Libraries and load the  dataset We will first inspect the dataset to understand its structure.
"""

#import Libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv('/content/social_media_vs_productivity.csv') #Load Dataset

# display  first 5 rows
data.head()

data.info()##show num of row , col ,datatype and missing value

data.describe() # show missing value , mean , std ( probablity)

"""# 2.Data Exploration

Before preprocessing, it's important to explore the data. if there are any missing values and check outlier and visualization
"""

data.isnull().sum()

#fill the numric datatype of median
for col in data.select_dtypes(include=['int64', 'float64']).columns:
    data[col] = data[col].fillna(data[col].median())

#fill the categorical datatype of mode

for col in data.select_dtypes(include=['object']).columns:
    data[col] = data[col].fillna(data[col].mode()[0])

print(data.isnull().sum()) #check fill missing value

"""# Data Preprocessing

we Encode categorical features , feature scaling ,Outlier Detection and Dimensionality Reduction
"""

# convert data categorical into (encoding)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in ["gender", "job_type", "social_platform_preference"]:
    data[col] = le.fit_transform(data[col])

"""check outlier"""

from scipy import stats
# Select only numeric columns for z-score calculation
numeric_data = data.select_dtypes(include=np.number)

z_scores = np.abs(stats.zscore(numeric_data))
outliers = (z_scores > 3)
outlier_counts = pd.Series(outliers.sum(axis=0), index=numeric_data.columns)
print("Number of outliers in each column:")
print(outlier_counts)

col = "daily_social_media_time"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(4,4))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["lightblue", "red"],
        startangle=90)
plt.title(f"{col} (Z-score)")
plt.show()

col = "number_of_notifications"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(5,5))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["skyblue", "red"],
        startangle=90)
plt.title(f"Outliers in {col}")
plt.show()

col = "work_hours_per_day"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(5,5))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["skyblue", "red"],
        startangle=90)
plt.title(f"Outliers in {col}")
plt.show()

col = "screen_time_before_sleep"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(5,5))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["skyblue", "red"],
        startangle=90)
plt.title(f"Outliers in {col}")
plt.show()

col = "coffee_consumption_per_day"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(5,5))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["skyblue", "red"],
        startangle=90)
plt.title(f"Outliers in {col}")
plt.show()

col = "weekly_offline_hours"

# calc Z-score
mean = data[col].mean()
std = data[col].std()
z_scores = (data[col] - mean) / std

# num of outlier
outliers = np.abs(z_scores) > 3
outlier_count = outliers.sum()
normal_count = len(data[col]) - outlier_count

print(f"{col}: Outliers = {outlier_count}, Normal = {normal_count}")

plt.figure(figsize=(5,5))
plt.pie([normal_count, outlier_count],
        labels=["Normal", "Outliers"],
        autopct='%1.1f%%',
        colors=["skyblue", "red"],
        startangle=90)
plt.title(f"Outliers in {col}")
plt.show()

def clean_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR


    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])
    return df

# col of outlier
cols_with_outliers = ["daily_social_media_time", "number_of_notifications", "work_hours_per_day",
                      "screen_time_before_sleep", "coffee_consumption_per_day","weekly_offline_hours"]

# clean oulier of cols
for col in cols_with_outliers:
    scaled_df = clean_outliers_iqr(data, col)

print(" Outliers cleand ")

# col of outlier
cols_with_outliers = ["daily_social_media_time", "number_of_notifications", "work_hours_per_day",
                      "screen_time_before_sleep", "coffee_consumption_per_day","weekly_offline_hours"]

#draw histo gram of each col
for col in cols_with_outliers:
    plt.figure(figsize=(6,4))
    plt.hist(scaled_df[col], bins=30, color="skyblue", edgecolor="black")
    plt.title(f"Histogram of {col} after Outlier Cleaning")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

"""scalling"""

from sklearn.preprocessing import StandardScaler
# Select only numeric columns for z-score calculation
numeric_data = data.select_dtypes(include=np.number)
# Apply scaling
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_data)

scaled_df = pd.DataFrame(scaled_data, columns=numeric_data.columns)

print(scaled_df.head())

# correlation matrix
corr = scaled_df.corr()

plt.figure(figsize=(12,8))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f", cbar=True)
plt.title("Correlation Matrix", fontsize=16)
plt.show()

drop_features = [
    "actual_productivity_score",
    "age",
    "job_satisfaction_score"
]


df_selected = data.drop(columns=drop_features)

print("Remaining features after selection:")
print(df_selected.columns.tolist())

"""# Apply Agglomerative Clustering"""

from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as sch

plt.figure(figsize=(10, 7))
dendrogram = sch.dendrogram(sch.linkage(df_selected, method='ward'))
plt.title("Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Euclidean distances")
plt.show()

n_clusters = 2 #num choice from dendogram
# Agglomerative Clustering
agg_clust = AgglomerativeClustering(n_clusters=n_clusters, metric='euclidean', linkage='ward')
labels_agg = agg_clust.fit_predict(df_selected)

from sklearn.metrics import silhouette_score
#calc Silhouette Score
sil_score = silhouette_score(df_selected, labels_agg)
print(f"Agglomerative Clustering Silhouette Score: {sil_score:.3f}")

for k in range(2, 10):
    model = AgglomerativeClustering(n_clusters=k, linkage="ward")
    labels = model.fit_predict(df_selected)
    sil = silhouette_score(df_selected, labels)
    print(f"Clusters: {k}, Silhouette: {sil:.3f}")

best_k = 3
model = AgglomerativeClustering(n_clusters=best_k, linkage='ward')
labels = model.fit_predict(df_selected)

"""# DBSCAN"""

from sklearn.neighbors import NearestNeighbors


neighbors = NearestNeighbors(n_neighbors=5)
neighbors_fit = neighbors.fit(df_selected)
distances, indices = neighbors_fit.kneighbors(df_selected)

distances = np.sort(distances[:, 4])  # 4 = min_samples - 1
plt.plot(distances)
plt.title("k-distance Graph")
plt.xlabel("Points sorted by distance")
plt.ylabel("4th Nearest Neighbor Distance")
plt.show()

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=6, min_samples=4)
labels = dbscan.fit_predict(df_selected)

from sklearn.metrics import silhouette_score

mask = labels != -1
filtered_X = df_selected.iloc[mask]
filtered_labels = labels[mask]

# Silhouette Score
score = silhouette_score(filtered_X, filtered_labels)
print("Silhouette Score:", score)

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_scaled = pca.fit_transform(df_selected)

min_samples = 4
neighbors = NearestNeighbors(n_neighbors=min_samples)
neighbors_fit = neighbors.fit(X_scaled)
distances, indices = neighbors_fit.kneighbors(X_scaled)


distances = np.sort(distances[:, min_samples-1])
plt.figure(figsize=(8,6))
plt.plot(distances)
plt.xlabel("Points sorted by distance")
plt.ylabel(f"{min_samples}-th Nearest Neighbor Distance")
plt.title("Elbow Method for DBSCAN (eps)")
plt.show()

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.2, min_samples=12)
labels = dbscan.fit_predict(X_scaled)

from sklearn.metrics import silhouette_score

mask = labels != -1
filtered_X = X_scaled[mask]
filtered_labels = labels[mask]

# Silhouette Score
score = silhouette_score(filtered_X, filtered_labels)
print("Silhouette Score:", score)

